# Generated by Django 4.1.7 on 2023-03-18 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GEN", "GENERAL"),
                            ("MUS", "MUSIC"),
                            ("ENT", "ENTERTAINMENT"),
                            ("LIT", "LITERATURE"),
                            ("ART", "ART"),
                            ("SPO", "SPORT"),
                            ("SCI", "SCIENCE"),
                            ("BIZ", "BUSINESS"),
                            ("TEC", "TECHNOLOGY"),
                        ],
                        default="GEN",
                        max_length=3,
                    ),
                ),
                ("question", models.TextField(blank=True)),
                ("question_urls", models.JSONField(blank=True)),
                ("answer", models.TextField(blank=True)),
                ("answer_urls", models.JSONField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
