# Generated by Django 4.1.7 on 2023-03-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_urls",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_urls",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
