# Generated by Django 4.1.7 on 2023-03-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_question_answer_urls_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="used_for",
            field=models.TextField(default="UNASSIGNED"),
        ),
    ]
