# Generated by Django 4.1.7 on 2023-03-21 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_question_visible_to_friends"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_given", models.TextField(default="")),
                ("is_checked", models.BooleanField(default=False)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "answered_at",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                (
                    "answerer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.question"
                    ),
                ),
            ],
        ),
    ]
