# Generated by Django 4.1.7 on 2023-03-21 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0006_friendanswer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendanswer",
            unique_together={("question", "answerer")},
        ),
    ]
