# Generated by Django 4.1.7 on 2023-06-02 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0007_alter_friendanswer_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="make_answer_visible",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fs_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fs_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendshiprequests",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fr_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendshiprequests",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fr_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[
                    ("GEN", "GENERAL"),
                    ("MUS", "MUSIC"),
                    ("ENT", "ENTERTAINMENT"),
                    ("LIT", "LITERATURE"),
                    ("ART", "ART"),
                    ("SPO", "SPORT"),
                    ("SCI", "SCIENCE"),
                    ("BIZ", "BUSINESS"),
                    ("TEC", "TECHNOLOGY"),
                    ("HIS", "HISTORY"),
                ],
                default="GEN",
                max_length=3,
            ),
        ),
    ]
